global:
  smtp_smarthost: 'localhost:25'
  smtp_from: 'fake@email.com'
route:
  receiver: example-email
  group_by: [alertname]
receivers:
 - name: example-email
   email_configs:
    - to: 'fake@email.com'