services:
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus-c5-python.yml:/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
  hello-world:
    build: .
    ports:
      - 8080:80
      - 8001:8001
