---
version: "3.9"
services:
  myapp:
    build: .
    ports:
      - 8080:8080
      - 8081:8081

  prometheus:
    image: prom/prometheus:v2.40.4
    ports:
      - 9090:9090
    volumes:
      - ./prometheus-c4.yml:/etc/prometheus/prometheus.yml
