---
global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:

rule_files:

scrape_configs:
- job_name: myapp
  static_configs:
  - targets: ["myapp:8081"]
- job_name: pushgateway
  honor_labels: true
  static_configs:
  - targets:
    - localhost:9091