---
global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:

rule_files:

scrape_configs:
- job_name: myapp
  static_configs:
  - targets: ["myapp:8081"]

# global:
#   scrape_interval: 10s
# scrape_configs:
#  - job_name: prometheus
#    static_configs:
#     - targets:
#       # Use host.docker.internal in place of localhost
#       - host.docker.internal:9090
#  - job_name: gunicorn-app
#    static_configs:
#     - targets:
#       # Use host.docker.internal in place of localhost
#       - host.docker.internal:8000