services:
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus-c4.yml:/etc/prometheus/prometheus.yml"
    networks:
      - localprom
    ports:
      - 9090:9090
  gunicorn-app:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 python-examples.4-4-gunicorn-app:app
    networks:
      - localprom
    ports:
      - 8080:80
      - 8000:8000
networks:
  localprom:
    driver: bridge
