# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  
scrape_configs:
  - job_name: 'kubelet'
    kubernetes_sd_configs:
    - role: node # Should discover 1 target per Kubelet
    scheme: https # Sheme required because Kubelet serves metrics over https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: true # Must be used with Minikube to skipp the CA verification.
    authorization:
      credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token