services:
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus-c3.yml:/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
  hello-world:
    build: .
    ports:
      - 8080:80
      - 8000:8000
