global:
  scrape_interval: 10s
scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
      # Use host.docker.internal in place of localhost
      - host.docker.internal:9090
 - job_name: hello-world-app
   static_configs:
    - targets:
      # Use host.docker.internal in place of localhost
      - host.docker.internal:8000